# Generated by Django 3.0.8 on 2020-07-08 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0002_auto_20200708_1033'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='activityPeriod',
            new_name='activity',
        ),
    ]
